Sequelize Migrations Working
hernan-dp/we-chat-server pull request #1
Opened 2020-01-21 11:59 UTC by hernan-dp

2020-01-22 12:45 UTC, rdemasi requested changes

2020-01-22 12:45 UTC, rdemasi commented on src/migrations/20200121111445-create-user.js
> +        allowNull: true
firstName and lastName should be allowNull false here and also on the model

2020-01-22 12:45 UTC, rdemasi commented on src/models/user.js
> +};
Add new line here

2020-01-22 12:45 UTC, rdemasi commented on src/models/user.js
> +  };
remove semicolon here. Please, run standarjs

2020-01-24 17:11 UTC, nahudalla approved these changes

2020-01-24 17:14 UTC, rdemasi approved these changes
LGTM

2020-01-24 17:14 UTC, merged