Passport configuration and current-user query and resolver added
hernan-dp/we-chat-server pull request #6
Opened 2020-02-21 03:24 UTC by hernan-dp

2020-02-21 11:54 UTC, abelosorio requested changes

2020-02-21 11:54 UTC, abelosorio commented on src/controllers/user-controller.js
> +export const userlogged = async (_, _, { req }) => {
You aren't performing any asynchronous tasks here.

2020-02-21 11:54 UTC, abelosorio commented on src/index.js
> +    throw Error(error)
When you catch general errors, the `error` object could be an instance of any type of error. Here, you're always converting this error to the `Error` class and, potentially, losing information. I'd suggest changing this to:
```javascript
} catch (error) {
  throw error
}
```

2020-02-21 11:54 UTC, abelosorio commented on src/index.js
> +    if (!user) throw new Error('you must be logged in')
The job of `context` is to set the context, not to validate if the user is authenticated. This error should not be here. You may want to have some queries/mutations to even non-authenticated users and, with this logic, it won't allow it.

2020-02-21 11:54 UTC, abelosorio commented on src/schema/resolvers/user-resolver.js
> +    signin: userController.signIn,
No trailing commas.

2020-02-21 11:54 UTC, abelosorio commented on src/schema/resolvers/user-resolver.js
> +
No blank spaces at the end of an object.

2020-02-26 13:21 UTC, rdemasi approved these changes

2020-02-26 13:21 UTC, merged